[server]
listen_addr = "127.0.0.1:8080"
template_autoreload = false

[metrics]
enabled = false

[site]
title = "Alhambra Luckenwalde"
tagline = "Musik- und Kulturförderverein e.V."
description = "Der Musik- und Kulturförderverein e.V. veranstaltet und unterstützt kulturelle Projekte in Luckenwalde und Umgebung, und betreibt im ehemaligen Alhambra Kino am Markt eine Bar."

[[site.links]]
title = "Instagram"
href = "https://www.instagram.com/alhambra_luckenwalde"
doors = true

[[site.links]]
title = "Facebook"
href = "https://www.facebook.com/musikundkultur"

[[site.links]]
title = "Impressum"
href = "/impressum"

[calendar]
# This can also be set to `google-calendar` in the production config once
# support for it is implemented.
event_source = "static"

# List of events used by the `static` event source.
events = [
    # 2022
    { start_date = "2022-10-28T19:00:00+01:00", title = "Halloween-Party" },
    { start_date = "2022-11-04T19:00:00+01:00", title = "Geschlossene Gesellschaft" },
    { start_date = "2022-11-18T19:00:00+01:00", title = "Kneipenquiz" },
    { start_date = "2022-12-02T19:00:00+01:00", title = "Vorverkaufsparty Weihnachtskonzert" },
    { start_date = "2022-12-09T19:00:00+01:00", title = "Lesung" },
    { start_date = "2022-12-25T19:00:00+01:00", title = "Weihnachtskonzert" },
    # 2023
    { start_date = "2023-01-14T18:00:00+01:00", title = "Privatveranstaltung" },
    { start_date = "2023-01-20T18:00:00+01:00", title = "Privatveranstaltung" },
    { start_date = "2023-01-27T18:00:00+01:00", title = "Kneipenquiz" },
    { start_date = "2023-01-28T18:00:00+01:00", title = "Privatveranstaltung" },
    { start_date = "2023-02-03T18:00:00+01:00", title = "Barabend" },
    { start_date = "2023-02-10T18:00:00+01:00", title = "Barabend" },
    { start_date = "2023-02-17T18:00:00+01:00", title = "Smith & Smart / DJ Cutrock" },
    { start_date = "2023-02-24T18:00:00+01:00", title = "Barabend" },
    { start_date = "2023-03-03T18:00:00+01:00", title = "Kassettenriccardo & Support" },
    { start_date = "2023-03-10T18:00:00+01:00", title = "Cocktail Night" },
    { start_date = "2023-03-17T17:00:00+01:00", title = "Till Burgwächter (Lesung)" },
    { start_date = "2023-03-24T18:00:00+01:00", title = "Barabend" },
    { start_date = "2023-03-31T17:00:00+01:00", title = "Kollektiv:proton Kunstprojekt & Filmvorführung" },
    { start_date = "2023-03-31T18:00:00+01:00", title = "Barabend" },
    { start_date = "2023-04-21T18:00:00+01:00", title = "Barabend" },
    { start_date = "2023-04-28T18:00:00+01:00", title = "Kneipenquiz" },
    { start_date = "2023-04-29T18:00:00+01:00", title = "Geschlossene Gesellschaft" },
]
